version: 2
jobs:
  bch:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker image
          command: docker build --rm -t btcpool_bch --build-arg BUILD_ENV_TAG=bch-0.18.5 --build-arg BUILD_TYPE=Debug --build-arg BUILD_JOBS=2 --build-arg WORK_WITH_STRATUM_SWITCHER=OFF .
      - run:
          name: Run unit tests
          command: docker run --rm btcpool_bch /work/btcpool/build/unittest
workflows:
  version: 2
  build_and_test:
    jobs:
      - bch
