version: 2
jobs:
  bch:
    docker:
      - image: btccom/btcpool_build:bch-0.18.5
    steps:
      - checkout
      - run:
          name: Run CMake
          command: |
            mkdir build && cd build && \
            cmake -DCMAKE_BUILD_TYPE=Debug -DCHAIN_SRC_ROOT=/work/bitcoin -DCHAIN_TYPE=$CHAIN_TYPE -DJOBS=2  ..
      - run:
          name: Build btcpool
          command: cd build && make -j2
      - run:
          name: Run unit tests
          command: cd build && make test
      - run:
          name: Send failure notification
          command: curl $BEARYCHAT_WEBHOOK -H 'Content-Type:application/json' -d "{\"text\":\"[$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_JOB/$CIRCLE_BUILD_NUM]($CIRCLE_BUILD_URL) failed\"}"
          when: on_fail
      - run:
          name: Send success notification
          command: curl $BEARYCHAT_WEBHOOK -H 'Content-Type:application/json' -d "{\"text\":\"[$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_JOB/$CIRCLE_BUILD_NUM]($CIRCLE_BUILD_URL) succeeded\"}"
          when: on_success
workflows:
  version: 2
  build_and_test:
    jobs:
      - bch
