version: 2.1

commands:
  build_and_push_base_image:
    parameters:
      dockerfile:
        type: string
      tag:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker registry login
          command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin $DOCKER_SERVER
      - run:
          name: Build base image
          command: |
            cd docker/btcpool/base-image && \
            docker build --rm -t $DOCKER_SERVER/$BASE_IMAGE_REPO:<<parameters.tag>> -f <<parameters.dockerfile>> .
      - run:
          name: Push base image
          command: docker push $DOCKER_SERVER/$BASE_IMAGE_REPO:<<parameters.tag>>
  build_and_run_unit_tests_single_chain:
    steps:
      - checkout
      - run:
          name: Run CMake
          command: |
            mkdir build && cd build && \
            cmake -DCMAKE_BUILD_TYPE=Debug -DCHAIN_SRC_ROOT=/work/blockchain -DCHAIN_TYPE=$CHAIN_TYPE -DJOBS=2  ..
      - run:
          name: Build btcpool
          command: cd build && make -j2
      - run:
          name: Run unit tests
          command: cd build && make test
  build_and_push_deploy_image:
    parameters:
      base:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker registry login
          command: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin $DOCKER_SERVER
      - run:
          name: Build deploy image
          command: |
            docker build --rm -f docker/btcpool/deploy/Dockerfile \
              -t $DOCKER_SERVER/$DEPLOY_IMAGE_REPO:${CIRCLE_TAG}_<<parameters.base>> \
              --build-arg BASE_IMAGE=$DOCKER_SERVER/$BASE_IMAGE_REPO:<<parameters.base>> \
              --build-arg BUILD_JOBS=2 .
      - run:
          name: Push deploy image
          command: docker push $DOCKER_SERVER/$DEPLOY_IMAGE_REPO:${CIRCLE_TAG}_<<parameters.base>>
  

jobs:
  build_and_push_base_image_lint:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_base_image:
          dockerfile: Dockerfile.lint
          tag: lint
  build_and_push_base_image_bch:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_base_image:
          dockerfile: Dockerfile.bch
          tag: bch-0.18.5
  build_and_push_base_image_btc:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_base_image:
          dockerfile: Dockerfile.btc
          tag: btc-0.16.3
  build_and_push_base_image_sbtc:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_base_image:
          dockerfile: Dockerfile.sbtc
          tag: sbtc-0.16.2
  build_and_push_base_image_ubtc:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_base_image:
          dockerfile: Dockerfile.ubtc
          tag: ubtc-2.3.0.1
  build_and_push_base_image_ltc:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_base_image:
          dockerfile: Dockerfile.ltc
          tag: ltc-0.16.3
  build_and_push_base_image_zec:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_base_image:
          dockerfile: Dockerfile.zec
          tag: zec-2.0.4
  check_clang_format:
    docker:
      - image: $DOCKER_SERVER/$BASE_IMAGE_REPO:lint
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name: Run clang-format
          command: ./run-clang-format.sh && git diff --exit-code
  build_and_run_unit_tests_bch:
    docker:
      - image: $DOCKER_SERVER/$BASE_IMAGE_REPO:bch-0.18.5
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - build_and_run_unit_tests_single_chain
  build_and_run_unit_tests_btc:
    docker:
      - image: $DOCKER_SERVER/$BASE_IMAGE_REPO:btc-0.16.3
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - build_and_run_unit_tests_single_chain
  build_and_run_unit_tests_sbtc:
    docker:
      - image: $DOCKER_SERVER/$BASE_IMAGE_REPO:sbtc-0.16.2
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - build_and_run_unit_tests_single_chain
  build_and_run_unit_tests_ubtc:
    docker:
      - image: $DOCKER_SERVER/$BASE_IMAGE_REPO:ubtc-2.3.0.1
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - build_and_run_unit_tests_single_chain
  build_and_run_unit_tests_ltc:
    docker:
      - image: $DOCKER_SERVER/$BASE_IMAGE_REPO:ltc-0.16.3
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - build_and_run_unit_tests_single_chain
  build_and_run_unit_tests_zec:
    docker:
      - image: $DOCKER_SERVER/$BASE_IMAGE_REPO:zec-2.0.4
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - build_and_run_unit_tests_single_chain
  build_and_push_deploy_image_bch:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_deploy_image:
          base: bch-0.18.5
  build_and_push_deploy_image_btc:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_deploy_image:
          base: btc-0.16.3
  build_and_push_deploy_image_sbtc:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_deploy_image:
          base: sbtc-0.16.2
  build_and_push_deploy_image_ubtc:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_deploy_image:
          base: ubtc-2.3.0.1
  build_and_push_deploy_image_ltc:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_deploy_image:
          base: ltc-0.16.3
  build_and_push_deploy_image_zec:
    docker:
      - image: circleci/golang
    steps:
      - build_and_push_deploy_image:
          base: zec-2.0.4

workflows:
  version: 2
  build_and_push_base_images:
    jobs:
      - build_and_push_base_image_lint:
          filters:
            tags:
              only: /.*base-image.*/
            branches:
              ignore: /.*/
      - build_and_push_base_image_bch:
          filters:
            tags:
              only: /.*base-image.*/
            branches:
              ignore: /.*/
      - build_and_push_base_image_btc:
          filters:
            tags:
              only: /.*base-image.*/
            branches:
              ignore: /.*/
      - build_and_push_base_image_sbtc:
          filters:
            tags:
              only: /.*base-image.*/
            branches:
              ignore: /.*/
      - build_and_push_base_image_ubtc:
          filters:
            tags:
              only: /.*base-image.*/
            branches:
              ignore: /.*/
      - build_and_push_base_image_ltc:
          filters:
            tags:
              only: /.*base-image.*/
            branches:
              ignore: /.*/
      - build_and_push_base_image_zec:
          filters:
            tags:
              only: /.*base-image.*/
            branches:
              ignore: /.*/
  build_and_run_unit_tests_all_chains:
    jobs:
      - check_clang_format
      - build_and_run_unit_tests_bch:
          requires:
            - check_clang_format
      - build_and_run_unit_tests_btc:
          requires:
            - check_clang_format
      - build_and_run_unit_tests_sbtc:
          requires:
            - check_clang_format
      - build_and_run_unit_tests_ubtc:
          requires:
            - check_clang_format
      - build_and_run_unit_tests_ltc:
          requires:
            - check_clang_format
      - build_and_run_unit_tests_zec:
          requires:
            - check_clang_format
  build_and_push_deploy_images:
    jobs:
      - build_and_push_deploy_image_bch:
          filters:
            tags:
              ignore: /.*base-image.*/
            branches:
              ignore: /.*/
      - build_and_push_deploy_image_btc:
          filters:
            tags:
              ignore: /.*base-image.*/
            branches:
              ignore: /.*/
      - build_and_push_deploy_image_sbtc:
          filters:
            tags:
              ignore: /.*base-image.*/
            branches:
              ignore: /.*/
      - build_and_push_deploy_image_ubtc:
          filters:
            tags:
              ignore: /.*base-image.*/
            branches:
              ignore: /.*/
      - build_and_push_deploy_image_ltc:
          filters:
            tags:
              ignore: /.*base-image.*/
            branches:
              ignore: /.*/
      - build_and_push_deploy_image_zec:
          filters:
            tags:
              ignore: /.*base-image.*/
            branches:
              ignore: /.*/
