version: 2.1

jobs:
  check_clang_format:
    docker:
      - image: $BASE_IMAGE_SERVER/$BASE_IMAGE_REPO:lint
        auth:
          username: $BASE_IMAGE_USERNAME
          password: $BASE_IMAGE_PASSWORD
    steps:
      - checkout
      - run:
          name: Run clang-format
          command: ./run-clang-format.sh && git diff --exit-code
  build_and_run_unit_tests:
    parameters:
      base:
        type: string
    docker:
      - image: $BASE_IMAGE_SERVER/$BASE_IMAGE_REPO:<<parameters.base>>
        auth:
          username: $BASE_IMAGE_USERNAME
          password: $BASE_IMAGE_PASSWORD
    steps:
      - checkout
      - run:
          name: Run CMake
          command: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DCHAIN_SRC_ROOT=/work/blockchain -DCHAIN_TYPE=$CHAIN_TYPE -DJOBS=2  ..
      - run:
          name: Build btcpool
          command: cd build && make -j2
      - run:
          name: Run unit tests
          command: cd build && make test

workflows:
  version: 2
  build_and_run_unit_tests_all_chains:
    jobs:
      - check_clang_format
      - build_and_run_unit_tests:
          name: build_and_run_unit_tests@bch-0.18.5
          base: bch-0.18.5
          requires:
            - check_clang_format
      - build_and_run_unit_tests:
          name: build_and_run_unit_tests@btc-0.16.3
          base: btc-0.16.3
          requires:
            - check_clang_format
      - build_and_run_unit_tests:
          name: build_and_run_unit_tests@sbtc-0.16.2
          base: sbtc-0.16.2
          requires:
            - check_clang_format
      - build_and_run_unit_tests:
          name: build_and_run_unit_tests@ubtc-2.5.0.1
          base: ubtc-2.5.0.1
          requires:
            - check_clang_format
      - build_and_run_unit_tests:
          name: build_and_run_unit_tests@ltc-0.16.3
          base: ltc-0.16.3
          requires:
            - check_clang_format
      - build_and_run_unit_tests:
          name: build_and_run_unit_tests@zec-2.0.4
          base: zec-2.0.4
          requires:
            - check_clang_format
